---
- hosts: all
  become: true
  tasks:
  - name: install maven
    apt:
      pkg: maven
      state: present
    notify: run update
  - name: install docker
    apt:
      pkg: docker.io
      state: present
  - name: start docker service
    service:
      name: docker
      state: started
      enabled: true
  - name: deploy my-test-app application
    command: sudo docker run -it -d -p 8085:8080 --name my-test-app rakeshiimt06/my-test-app:1.0
  handlers:
  - name: run update
    apt:
      update_cache: yes

